feat/lerna-setup
EdGraVill/apptoolkit pull request #1
Opened 2022-11-27 20:51 UTC by deleonn

- Added root scripts for the `@apptoolkit/form` pkg.
- Added .nvmrc with version 16.

2022-11-27 22:47 UTC, EdGraVill requested changes

2022-11-27 22:47 UTC, EdGraVill commented on package.json
> +    "form:start": "lerna run start --scope=@apptoolkit/form",
Este comando no hace nada, pero no sé si sería buena idea, por ejemplo en el start poner el storybook o mantener mejor el patrón estándar

2022-11-28 05:28 UTC, deleonn commented on package.json
> +    "form:start": "lerna run start --scope=@apptoolkit/form",
Si te parece podemos dejar el patron de `<pkg>:<script>` en el que la parte del script coincide con el script real del paquete. En este caso para storybook seria `form:storybook` y solamente removemos el script de `form:start` que no hace nada. Btw ya lo actualice en el ultimo commit.

2022-11-28 20:56 UTC, EdGraVill commented on package.json
> +    "form:start": "lerna run start --scope=@apptoolkit/form",
Va. Perfecto. Gracias

2022-11-28 20:56 UTC, EdGraVill approved these changes

2022-11-28 20:56 UTC, merged